const initialState = {
  deviceType: '',
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      oldPrice: '40',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      compare: true,
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: '',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: true,
      compare: false,
      image:
        'https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1329711/pexels-photo-1329711.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      oldPrice: '35',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favorite: true,
      compare: true,
      image:
        'https://images.pexels.com/photos/6782567/pexels-photo-6782567.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      oldPrice: '45',
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6758350/pexels-photo-6758350.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      oldPrice: '40',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6782577/pexels-photo-6782577.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: true,
      compare: true,
      image:
        'https://images.pexels.com/photos/6782468/pexels-photo-6782468.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      oldPrice: '65',
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6758398/pexels-photo-6758398.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      oldPrice: '50',
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6782473/pexels-photo-6782473.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      oldPrice: '',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6758769/pexels-photo-6758769.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6782472/pexels-photo-6782472.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 70,
      oldPrice: '90',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6758519/pexels-photo-6758519.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      oldPrice: '35',
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      oldPrice: '55',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3946657/pexels-photo-3946657.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      oldPrice: '',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4713245/pexels-photo-4713245.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6585740/pexels-photo-6585740.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6587906/pexels-photo-6587906.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 35,
      oldPrice: '45',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6316054/pexels-photo-6316054.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 25,
      oldPrice: '35',
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6316054/pexels-photo-6316054.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6585759/pexels-photo-6585759.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 40,
      oldPrice: '60',
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6492400/pexels-photo-6492400.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      oldPrice: '35',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6585619/pexels-photo-6585619.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      oldPrice: '40',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6444258/pexels-photo-6444258.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      oldPrice: '55',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2029722/pexels-photo-2029722.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-25',
      name: 'Aenean Ru Bristique 25',
      category: 'chair',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/963486/pexels-photo-963486.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-26',
      name: 'Aenean Ru Bristique 26',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2082090/pexels-photo-2082090.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-27',
      name: 'Aenean Ru Bristique 27',
      category: 'chair',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6180675/pexels-photo-6180675.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-28',
      name: 'Aenean Ru Bristique 28',
      category: 'chair',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-29',
      name: 'Aenean Ru Bristique 29',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4450334/pexels-photo-4450334.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-30',
      name: 'Aenean Ru Bristique 30',
      category: 'chair',
      price: 30,
      oldPrice: '40',
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/220749/pexels-photo-220749.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-31',
      name: 'Aenean Ru Bristique 31',
      category: 'chair',
      price: 30,
      oldPrice: '40',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/280471/pexels-photo-280471.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-32',
      name: 'Aenean Ru Bristique 32',
      category: 'chair',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/276534/pexels-photo-276534.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-33',
      name: 'Aenean Ru Bristique 33',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-34',
      name: 'Aenean Ru Bristique 34',
      category: 'chair',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-35',
      name: 'Aenean Ru Bristique 35',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6588591/pexels-photo-6588591.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-36',
      name: 'Aenean Ru Bristique 36',
      category: 'chair',
      price: 30,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6587894/pexels-photo-6587894.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-37',
      name: 'Aenean Ru Bristique 37',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/416320/pexels-photo-416320.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-38',
      name: 'Aenean Ru Bristique 38',
      category: 'chair',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2547555/pexels-photo-2547555.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      featured: true,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-39',
      name: 'Aenean Ru Bristique 39',
      category: 'chair',
      price: 35,
      oldPrice: '45',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6758784/pexels-photo-6758784.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-40',
      name: 'Aenean Ru Bristique 40',
      category: 'chair',
      price: 30,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6707628/pexels-photo-6707628.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-41',
      name: 'Aenean Ru Bristique 41',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/60342/pexels-photo-60342.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-42',
      name: 'Aenean Ru Bristique 42',
      category: 'chair',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6198651/pexels-photo-6198651.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-43',
      name: 'Aenean Ru Bristique 43',
      category: 'chair',
      price: 30,
      oldPrice: '40',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/112474/pexels-photo-112474.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-44',
      name: 'Aenean Ru Bristique 44',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4846461/pexels-photo-4846461.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-45',
      name: 'Aenean Ru Bristique 45',
      category: 'chair',
      price: 30,
      oldPrice: '40',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/241520/pexels-photo-241520.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-46',
      name: 'Aenean Ru Bristique 46',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6186506/pexels-photo-6186506.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-47',
      name: 'Aenean Ru Bristique 47',
      category: 'chair',
      price: 45,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6198665/pexels-photo-6198665.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-48',
      name: 'Aenean Ru Bristique 48',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/5998127/pexels-photo-5998127.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-49',
      name: 'Aenean Ru Bristique 49',
      category: 'sofa',
      price: 30,
      oldPrice: '40',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-50',
      name: 'Aenean Ru Bristique 50',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3757055/pexels-photo-3757055.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-51',
      name: 'Aenean Ru Bristique 51',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6143344/pexels-photo-6143344.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-52',
      name: 'Aenean Ru Bristique 52',
      category: 'sofa',
      price: 30,
      oldPrice: '40',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1571471/pexels-photo-1571471.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-53',
      name: 'Aenean Ru Bristique 53',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1571457/pexels-photo-1571457.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-54',
      name: 'Aenean Ru Bristique 54',
      category: 'sofa',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6758242/pexels-photo-6758242.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-55',
      name: 'Aenean Ru Bristique 55',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3965534/pexels-photo-3965534.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-56',
      name: 'Aenean Ru Bristique 56',
      category: 'sofa',
      price: 55,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6758245/pexels-photo-6758245.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-57',
      name: 'Aenean Ru Bristique 57',
      category: 'sofa',
      price: 30,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6438762/pexels-photo-6438762.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-58',
      name: 'Aenean Ru Bristique 58',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-59',
      name: 'Aenean Ru Bristique 59',
      category: 'sofa',
      price: 30,
      oldPrice: '40',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6782349/pexels-photo-6782349.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-60',
      name: 'Aenean Ru Bristique 60',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6527037/pexels-photo-6527037.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-61',
      name: 'Aenean Ru Bristique 61',
      category: 'sofa',
      price: 45,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4857784/pexels-photo-4857784.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-62',
      name: 'Aenean Ru Bristique 62',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6492397/pexels-photo-6492397.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-63',
      name: 'Aenean Ru Bristique 63',
      category: 'sofa',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6527052/pexels-photo-6527052.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-64',
      name: 'Aenean Ru Bristique 64',
      category: 'sofa',
      price: 40,
      oldPrice: '50',
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4846097/pexels-photo-4846097.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-65',
      name: 'Aenean Ru Bristique 65',
      category: 'sofa',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6782569/pexels-photo-6782569.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-66',
      name: 'Aenean Ru Bristique 66',
      category: 'sofa',
      price: 55,
      oldPrice: '65',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6782480/pexels-photo-6782480.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-67',
      name: 'Aenean Ru Bristique 67',
      category: 'sofa',
      price: 30,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6588579/pexels-photo-6588579.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-68',
      name: 'Aenean Ru Bristique 68',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6585764/pexels-photo-6585764.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-69',
      name: 'Aenean Ru Bristique 69',
      category: 'sofa',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6588599/pexels-photo-6588599.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-70',
      name: 'Aenean Ru Bristique 70',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6758346/pexels-photo-6758346.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-71',
      name: 'Aenean Ru Bristique 71',
      category: 'sofa',
      price: 30,
      oldPrice: '40',
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6316055/pexels-photo-6316055.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-72',
      name: 'Aenean Ru Bristique 72',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6312353/pexels-photo-6312353.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-73',
      name: 'Aenean Ru Bristique 73',
      category: 'table',
      price: 30,
      oldPrice: '40',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/890669/pexels-photo-890669.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-74',
      name: 'Aenean Ru Bristique 74',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2092058/pexels-photo-2092058.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-75',
      name: 'Aenean Ru Bristique 75',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6707628/pexels-photo-6707628.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-76',
      name: 'Aenean Ru Bristique 76',
      category: 'table',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6707631/pexels-photo-6707631.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-77',
      name: 'Aenean Ru Bristique 77',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-78',
      name: 'Aenean Ru Bristique 78',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/7401883/pexels-photo-7401883.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-79',
      name: 'Aenean Ru Bristique 79',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/5244041/pexels-photo-5244041.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-80',
      name: 'Aenean Ru Bristique 80',
      category: 'table',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/545012/pexels-photo-545012.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-81',
      name: 'Aenean Ru Bristique 81',
      category: 'table',
      price: 55,
      oldPrice: '60',
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2041003/pexels-photo-2041003.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-82',
      name: 'Aenean Ru Bristique 82',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4554438/pexels-photo-4554438.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-83',
      name: 'Aenean Ru Bristique 83',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/5703542/pexels-photo-5703542.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-84',
      name: 'Aenean Ru Bristique 84',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4473995/pexels-photo-4473995.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-85',
      name: 'Aenean Ru Bristique 85',
      category: 'table',
      price: 20,
      oldPrice: '50',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4554421/pexels-photo-4554421.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-86',
      name: 'Aenean Ru Bristique 86',
      category: 'table',
      price: 50,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/7047481/pexels-photo-7047481.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-87',
      name: 'Aenean Ru Bristique 87',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6862459/pexels-photo-6862459.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-88',
      name: 'Aenean Ru Bristique 88',
      category: 'table',
      price: 40,
      oldPrice: '45',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/7402619/pexels-photo-7402619.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-89',
      name: 'Aenean Ru Bristique 89',
      category: 'table',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/7046931/pexels-photo-7046931.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-90',
      name: 'Aenean Ru Bristique 90',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/7222089/pexels-photo-7222089.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-91',
      name: 'Aenean Ru Bristique 91',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/7433147/pexels-photo-7433147.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-92',
      name: 'Aenean Ru Bristique 92',
      category: 'table',
      price: 50,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4939607/pexels-photo-4939607.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-93',
      name: 'Aenean Ru Bristique 93',
      category: 'table',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/5704565/pexels-photo-5704565.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-94',
      name: 'Aenean Ru Bristique 94',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/5712141/pexels-photo-5712141.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-95',
      name: 'Aenean Ru Bristique 95',
      category: 'table',
      price: 30,
      oldPrice: '40',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3747082/pexels-photo-3747082.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-96',
      name: 'Aenean Ru Bristique 96',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/7237069/pexels-photo-7237069.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-97',
      name: 'Aenean Ru Bristique 97',
      category: 'dining',
      price: 55,
      oldPrice: '60',
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1457841/pexels-photo-1457841.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-98',
      name: 'Aenean Ru Bristique 98',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2029670/pexels-photo-2029670.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-99',
      name: 'Aenean Ru Bristique 99',
      category: 'dining',
      price: 30,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4577408/pexels-photo-4577408.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-100',
      name: 'Aenean RuBristique100',
      category: 'dining',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2287523/pexels-photo-2287523.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      featured: true,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-101',
      name: 'Aenean Ru Bristique 101',
      category: 'dining',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6297088/pexels-photo-6297088.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-102',
      name: 'Aenean Ru Bristique 102',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2504963/pexels-photo-2504963.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    },
    {
      id: 'aenean-ru-bristique-103',
      name: 'Aenean Ru Bristique 103',
      category: 'dining',
      price: 30,
      oldPrice: '40',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6585598/pexels-photo-6585598.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-104',
      name: 'Aenean Ru Bristique 104',
      category: 'dining',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2220120/pexels-photo-2220120.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    },
    {
      id: 'aenean-ru-bristique-105',
      name: 'Aenean Ru Bristique 105',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6207824/pexels-photo-6207824.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true, 
    },
    {
      id: 'aenean-ru-bristique-106',
      name: 'Aenean Ru Bristique 106',
      category: 'dining',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2089696/pexels-photo-2089696.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-107',
      name: 'Aenean Ru Bristique 107',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6758513/pexels-photo-6758513.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-108',
      name: 'Aenean Ru Bristique 108',
      category: 'dining',
      price: 35,
      oldPrice: '40',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6758283/pexels-photo-6758283.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-109',
      name: 'Aenean Ru Bristique 109',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/271696/pexels-photo-271696.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-110',
      name: 'Aenean Ru Bristique 110',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-111',
      name: 'Aenean Ru Bristique 111',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2290070/pexels-photo-2290070.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: 'aenean-ru-bristique-112',
      name: 'Aenean Ru Bristique 112',
      category: 'dining',
      price: 30,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4846461/pexels-photo-4846461.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-113',
      name: 'Aenean Ru Bristique 113',
      category: 'dining',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2306281/pexels-photo-2306281.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-114',
      name: 'Aenean Ru Bristique 114',
      category: 'dining',
      price: 50,
      oldPrice: '65',
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4262173/pexels-photo-4262173.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-115',
      name: 'Aenean Ru Bristique 115',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-116',
      name: 'Aenean Ru Bristique 116',
      category: 'dining',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/932095/pexels-photo-932095.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,  
    },
    {
      id: 'aenean-ru-bristique-117',
      name: 'Aenean Ru Bristique 117',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6269976/pexels-photo-6269976.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,  
    },
    {
      id: 'aenean-ru-bristique-118',
      name: 'Aenean Ru Bristique 118',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/7777702/pexels-photo-7777702.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: 'aenean-ru-bristique-119',
      name: 'Aenean Ru Bristique 119',
      category: 'dining',
      price: 35,
      oldPrice: '45',
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6608944/pexels-photo-6608944.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-120',
      name: 'Aenean Ru Bristique 120',
      category: 'dining',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/5778892/pexels-photo-5778892.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
  ],
  brands: [
    {
      id: '1',
      logo:
        'https://images.pexels.com/photos/988952/pexels-photo-988952.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
    },
    {
      id: '2',
      logo:
        'https://images.pexels.com/photos/1435750/pexels-photo-1435750.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: '3',
      logo:
        'https://images.pexels.com/photos/2921584/pexels-photo-2921584.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: '4',
      logo:
        'https://images.pexels.com/photos/4480519/pexels-photo-4480519.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: '5',
      logo:
        'https://images.pexels.com/photos/7719767/pexels-photo-7719767.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: '6',
      logo:
        'https://images.pexels.com/photos/1437318/pexels-photo-1437318.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: '7',
      logo:
        'https://images.pexels.com/photos/755992/pexels-photo-755992.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: '8',
      logo:
        'https://images.pexels.com/photos/988953/pexels-photo-988953.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: '9',
      logo:
        'https://images.pexels.com/photos/569996/pexels-photo-569996.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    },
    {
      id: '10',
      logo:
        'https://images.pexels.com/photos/258174/pexels-photo-258174.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: '11',
      logo:
        'https://images.pexels.com/photos/2983100/pexels-photo-2983100.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: '12',
      logo:
        'https://images.pexels.com/photos/7719767/pexels-photo-7719767.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
    },
  ],
  cart: {
    products: [],
  },

  promotions: [
    {
      id: 'promotion-1',
      image:
        'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      alt: 'promo-1',
      text: 'GUEST ROOM',
      text_bold: 'SOFA',
      text_percent: '-20%',
    },
    {
      id: 'promotion-2',
      image:
        'https://images.pexels.com/photos/205321/pexels-photo-205321.png?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      alt: 'promo-2',
      text: 'OFFICE',
      text_2: 'CHAIR',
      text_bold: 'COLLECTION',
      text_money: '$200.00',
    },
    {
      id: 'promotion-3',
      image:
        'https://images.pexels.com/photos/6636243/pexels-photo-6636243.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      alt: 'promo-3',
      text: 'SPECIAL',
      text_2: 'COLLECTION',
      text_content: 'SAVE UP 45% OF FURNITURE ',
    },
  ],

  promo_products: [
    {
      id: 'aenean-ru-bristique-1',
      oldPrice: 123,
      src:
        'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      alt: 'sofa',
      description: 'save up to 50% of all furniture',
    },
    {
      id: 'aenean-ru-bristique-2',
      oldPrice: 123,
      src:
        'https://images.pexels.com/photos/4505458/pexels-photo-4505458.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      alt: 'sofa',
      description: 'save up to 10%',
    },
    {
      id: 'aenean-ru-bristique-3',
      oldPrice: 123,
      src:
        'https://images.pexels.com/photos/4577654/pexels-photo-4577654.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      alt: 'sofa',
      description: 'buy one get one free',
    },
  ],

  feedback: [
    {
      id: '1',
      name: 'John Smith',
      feedback:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam maximus massa luctus, interdum dui ac, consequat lorem. Quisque id quam rhoncus, venenatis urna ac, malesuada urna.',
      img_src:
        'https://images.pexels.com/photos/1586996/pexels-photo-1586996.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: '2',
      name: 'Mike Tyson',
      feedback:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam maximus massa luctus, interdum dui ac, consequat lorem. Quisque id quam rhoncus, venenatis urna ac, malesuada urna.',
      img_src:
        'https://images.pexels.com/photos/3760809/pexels-photo-3760809.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      id: '3',
      name: 'George Furniture',
      feedback:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam maximus massa luctus, interdum dui ac, consequat lorem. Quisque id quam rhoncus, venenatis urna ac, malesuada urna.',
      img_src:
        'https://images.pexels.com/photos/3760263/pexels-photo-3760263.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
  ],
};

export default initialState;
